import { readFile, writeFile, mkdir, stat } from "node:fs/promises";
import { pruneSubtree, assembleTree } from "../src/lib/tree/assemble";
import { dedupeRaws } from "../src/lib/tree/dedupe";
import { markPlayable, prunePlayable, playableGenera, adaptiveCap, DEFAULT_CAP_DIALS } from "../src/lib/tree/playable";
import type { RawTaxon, TreeData } from "../src/lib/tree/types";
import { AVES, DINOSAURIA, NEORNITHES } from "../src/lib/tree/types";
import type { GenusAttribute, GenusAttributes } from "../src/lib/attributes";
import type { ImageCredits } from "../src/lib/image-credits";
import { enrichAge, isMesozoic, MESOZOIC_END_MA } from "../src/lib/geologic-time";
import { findConflicts, findDecisionCollisions, type NameConflict } from "../src/lib/tree/names";
import { NAME_DECISIONS } from "../src/lib/tree/name-decisions";

function renderReport(conflicts: NameConflict[]): string {
  const lines = [
    "# Name disagreements",
    "",
    "Auto-generated by `build:data`. Each row is a node whose Wikidata `en` label, P225 taxon",
    "name, and/or enwiki title disagree and that has NO entry in NAME_DECISIONS. The build fails",
    "while any remain. Resolve by adding the Q-id to `src/lib/tree/name-decisions.ts`.",
    "",
    conflicts.length === 0 ? "_None — all disagreements are decided._" : `${conflicts.length} undecided:`,
    "",
  ];
  for (const c of conflicts) {
    const parts = [
      `- **${c.id}**`,
      c.en ? `en=\`${c.en}\`` : null,
      c.taxonName ? `P225=\`${c.taxonName}\`` : null,
      c.enwikiTitle ? `enwiki=\`${c.enwikiTitle}\`` : null,
      c.redirectTarget ? `↳redirects→\`${c.redirectTarget}\`` : null,
    ].filter(Boolean);
    lines.push(parts.join("  "));
  }
  lines.push("");
  return lines.join("\n");
}

/** Ids of every genus at or below `rootId`. */
function generaUnder(tree: TreeData, rootId: string): string[] {
  const out: string[] = [];
  const stack = [rootId];
  while (stack.length) {
    const node = tree.nodes[stack.pop()!];
    if (!node) continue;
    if (node.isGenus) out.push(node.id);
    stack.push(...node.childrenIds);
  }
  return out;
}

async function main() {
  const raws: RawTaxon[] = JSON.parse(await readFile("data/raw-taxa.json", "utf8"));
  const pbdbByName: Record<string, GenusAttribute> = JSON.parse(await readFile("data/raw-pbdb.json", "utf8"));

  // GUARD 1 (input freshness): the raws are gitignored + machine-local, so a build can run against a
  // STALE pull. The state/formation clue fields arrived with the layered-clue harvest (e5c74eb); a
  // raw predating it has countries but ZERO state/province — and rebuilding from it silently wipes
  // location detail from the committed clues (this bit us 2026-07-17). Fail-closed: many locations
  // but no states == stale raw. Re-run `npm run fetch:pbdb`.
  {
    const vals = Object.values(pbdbByName);
    const withLoc = vals.filter((v) => v.discoveryLocation).length;
    const withState = vals.filter((v) => v.discoveryState).length;
    if (withLoc >= 100 && withState === 0) {
      console.error(`\n✗ data/raw-pbdb.json looks STALE: ${withLoc} genera have a country but 0 have a state/province.`);
      console.error("  This raw predates the state/formation harvest. Re-run `npm run fetch:pbdb` before building.");
      process.exit(1);
    }
  }

  let imageCredits: ImageCredits = {};
  try { imageCredits = JSON.parse(await readFile("data/image-credits.json", "utf8")); }
  catch { console.warn("no data/image-credits.json — images will keep Commons hotlinks"); }
  const dataVersion = new Date().toISOString().slice(0, 10);

  // When was the raw data last pulled? The raws are gitignored and only ever written by the
  // fetch scripts, so each file's mtime *is* its pull time. Take the OLDER of the two so the
  // footer never over-claims freshness (PBDB always trails Wikidata). Baked into a committed
  // meta.json here — the app reads that, never the filesystem — so the date can't drift.
  // Local calendar date (en-CA renders ISO YYYY-MM-DD) — a footer freshness label should match
  // the wall clock of whoever pulled, not UTC, which reads a day ahead on evening pulls.
  const [taxaStat, pbdbStat] = await Promise.all([stat("data/raw-taxa.json"), stat("data/raw-pbdb.json")]);
  const dataPulledAt = new Date(Math.min(taxaStat.mtimeMs, pbdbStat.mtimeMs)).toLocaleDateString("en-CA");

  // Name-disagreement gate: any node with ≥2 distinct name candidates and no decision blocks the
  // build. Always (re)write the committed report deterministically.
  const conflicts = findConflicts(raws, NAME_DECISIONS);
  await mkdir("data", { recursive: true });
  await writeFile("data/name-disagreements.md", renderReport(conflicts));
  if (conflicts.length > 0) {
    console.error(`\n✗ ${conflicts.length} undecided name disagreement(s). See data/name-disagreements.md`);
    console.error("  Add each Q-id to NAME_DECISIONS (src/lib/tree/name-decisions.ts) and rebuild.");
    process.exit(1);
  }

  // Decision-collision gate: a NAME_DECISIONS entry whose name exactly matches a different node
  // would silently MERGE the two in dedupe, collapsing a real clade rung. Fail closed.
  const collisions = findDecisionCollisions(raws, NAME_DECISIONS);
  if (collisions.length > 0) {
    console.error(`\n✗ ${collisions.length} NAME_DECISIONS collision(s) — each would merge a distinct clade:`);
    for (const c of collisions) console.error(`  decision ${c.id} -> "${c.name}" would merge into ${c.mergesInto.join(", ")}`);
    console.error("  Pick a non-colliding name, or use the forced-merge-target mechanism if a merge IS intended.");
    process.exit(1);
  }

  const structural = pruneSubtree(dedupeRaws(raws), NEORNITHES);
  const full = assembleTree(structural, DINOSAURIA, dataVersion);

  // Attributes keyed by genus id (match PBDB by name). Enrich each age into a legible layered
  // form — derive the coarse epoch, and a stage label from Ma when PBDB gave numbers-only — so
  // hasClue() sees a label for the numbers-only genera and they survive the notability prune.
  // Built against the FULL tree because the Mesozoic gate below needs ages to filter on; node
  // ids are stable across assembly, so these carry over to the pruned tree unchanged.
  const attrs: GenusAttributes = {};
  for (const n of Object.values(full.nodes)) {
    if (!n.isGenus || !pbdbByName[n.name]) continue;
    const raw = pbdbByName[n.name];
    const age = enrichAge(raw);
    attrs[n.id] = age ? { ...raw, ...age } : raw;
  }

  // Mesozoic gate: it's called Mesozooa. Drop any genus PBDB dates entirely after the K–Pg
  // boundary — the Eocene/Oligocene stem-parrot tail hanging off Aves, plus Cardiodon, a
  // Jurassic sauropod PBDB mis-dates to the Miocene via a homonym. Cutting genera from the raws
  // and re-assembling lets assembleTree drop any clade left childless (it keeps only nodes on a
  // root→genus path), so counts and depths stay honest without hand-maintenance.
  const postMesozoic = new Set(
    Object.values(full.nodes)
      .filter((n) => n.isGenus && !isMesozoic(attrs[n.id] ?? {}))
      .map((n) => n.id),
  );

  // Undated genera under Aves go too. Aves is the ONLY clade here that crosses the K–Pg, so it's
  // the only place a missing date can hide a Cenozoic taxon — elsewhere, undated is Mesozoic by
  // construction and keeping it costs nothing. Under Aves the undated tail is mostly Cenozoic
  // fossil birds Wikidata files here with no PBDB occurrences; undated means no clue, so they can
  // never be playable and only ever clutter Explore. Costs two real Mesozoic birds (Foshanornis,
  // Guildavis) that PBDB has no occurrences for — the price of not curating a name list by hand.
  for (const id of generaUnder(full, AVES)) {
    if (attrs[id]?.ageStartMa == null) postMesozoic.add(id);
  }
  const tree = assembleTree(
    structural.filter((r) => !postMesozoic.has(r.id)),
    DINOSAURIA,
    dataVersion,
  );
  // Rewrite Commons hotlinks to local /images paths + attach per-image credit. Only touch nodes
  // that have a downloaded thumbnail (credit entry present); leave the rest untouched so a node
  // whose harvest failed keeps whatever it had rather than pointing at a missing file.
  const { existsSync } = await import("node:fs");
  for (const node of Object.values(tree.nodes)) {
    if (!node.imageUrl) continue;
    const credit = imageCredits[node.id];
    if (!credit) { delete node.imageUrl; continue; } // no local file -> no image (falls back to ???)
    if (!existsSync(`public/images/${node.id}.webp`)) { delete node.imageUrl; continue; }
    node.imageUrl = `/images/${node.id}.webp`;
    if (credit.author) node.imageAuthor = credit.author;
    if (credit.licenseShort) node.imageLicense = credit.licenseShort;
    if (credit.licenseUrl) node.imageLicenseUrl = credit.licenseUrl;
  }

  markPlayable(tree); // base eligibility: genus + enwiki + family ancestor

  // Notability prune: needs a clue; keep ≤ diversity-scaled cap per terminal set.
  prunePlayable(tree, attrs, (members) =>
    adaptiveCap(members.map((n) => attrs[n.id]).filter((a): a is GenusAttribute => !!a), DEFAULT_CAP_DIALS),
  );

  const genera = Object.values(tree.nodes).filter((n) => n.isGenus);
  const playable = playableGenera(tree);
  const index = playable
    .map((n) => ({ id: n.id, name: n.name }))
    .sort((a, b) => a.name.localeCompare(b.name));

  // Emit clue attributes only for the final playable set.
  const clueOut: GenusAttributes = {};
  for (const n of playable) if (attrs[n.id]) clueOut[n.id] = attrs[n.id];

  // GUARD 2 (output regression): compare this build against the CURRENTLY-COMMITTED data and
  // fail-closed if key coverage drops sharply — a rebuild should never ship materially LESS than
  // what's committed unless a data change is intended. Catches any silent degradation (stale raw,
  // a broken parser, an accidental filter), not just the one Guard 1 knows about. Override for a
  // deliberate shrink with ALLOW_DATA_REGRESSION=1. Compares against the git-tracked file on disk;
  // skipped cleanly on first-ever build (no committed file to compare).
  {
    const clueLocNow = Object.values(clueOut).filter((a) => a.discoveryState).length;
    const playableNow = playable.length;
    let prev: { playable: number; clueLoc: number } | null = null;
    try {
      const prevAttrs: GenusAttributes = JSON.parse(await readFile("src/data/genus-attributes.json", "utf8"));
      const prevIdx: unknown[] = JSON.parse(await readFile("src/data/genera-index.json", "utf8"));
      prev = {
        playable: prevIdx.length,
        clueLoc: Object.values(prevAttrs).filter((a) => a.discoveryState).length,
      };
    } catch { /* first build — nothing committed to regress against */ }
    if (prev && !process.env.ALLOW_DATA_REGRESSION) {
      // >10% drop in either metric is the tripwire (well below normal fetch drift of a few %).
      const dropped = (was: number, now: number) => was > 0 && now < was * 0.9;
      const problems: string[] = [];
      if (dropped(prev.playable, playableNow)) problems.push(`playable pool ${prev.playable} → ${playableNow}`);
      if (dropped(prev.clueLoc, clueLocNow)) problems.push(`clues with location detail ${prev.clueLoc} → ${clueLocNow}`);
      if (problems.length) {
        console.error(`\n✗ build would REGRESS committed data:\n    ${problems.join("\n    ")}`);
        console.error("  A rebuild should not ship materially less than what's committed. Likely a stale raw pull —");
        console.error("  re-run `npm run fetch` (or `fetch:pbdb`). If the shrink is intentional, set ALLOW_DATA_REGRESSION=1.");
        process.exit(1);
      }
    }
  }

  await mkdir("src/data", { recursive: true });
  await writeFile("src/data/tree.json", JSON.stringify(tree));
  await writeFile("src/data/genera-index.json", JSON.stringify(index));
  await writeFile("src/data/genus-attributes.json", JSON.stringify(clueOut));
  await writeFile("src/data/meta.json", JSON.stringify({ dataPulledAt }));

  // Data-quality report.
  console.log("=== Mesozooa data build ===");
  console.log("dataVersion:        ", dataVersion);
  console.log("dataPulledAt:       ", dataPulledAt);
  console.log("raw taxa (pre-dedupe):", raws.length);
  console.log("after dedupe:       ", dedupeRaws(raws).length);
  console.log("total nodes:        ", Object.keys(tree.nodes).length);
  console.log("genera (all):       ", genera.length);
  console.log("post-Mesozoic cut:  ", postMesozoic.size, `(dated younger than ${MESOZOIC_END_MA} Ma, + undated under Aves)`);
  console.log("playable (pruned):  ", playable.length, `(adaptive cap ${DEFAULT_CAP_DIALS.capMin}–${DEFAULT_CAP_DIALS.capMax})`);
  console.log("clue attributes:    ", Object.keys(clueOut).length);
  console.log("genera w/o sitelink:", genera.filter((n) => n.sitelinks === 0).length);
  console.log("root count:         ", tree.nodes[DINOSAURIA].descendantGenusCount);
}

main().catch((e) => { console.error(e); process.exit(1); });
