// scripts/fetch-images.ts
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync, statSync } from "node:fs";
import type { RawTaxon } from "../src/lib/tree/types";
import { sanitizeArtist, type ImageCredit, type ImageCredits } from "../src/lib/image-credits";

const EXTS = ["jpg", "jpeg", "png", "gif", "svg", "webp", "tif", "tiff"];

const API = "https://commons.wikimedia.org/w/api.php";
const UA = "Mesozooa/0.1 (https://github.com/; dinosaur cladistics game)";
const THUMB_WIDTH = 640;
const IMG_DIR = "images-src";
const CREDITS_PATH = "data/image-credits.json";
const REPORT_PATH = "docs/superpowers/image-credits-report.md";
const FORCE = process.argv.includes("--force");

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

// The raw imageUrl is http://commons.wikimedia.org/wiki/Special:FilePath/<urlencoded file name>.
// Recover the bare "File:<name>" title the API wants.
function fileTitleFromUrl(imageUrl: string): string | null {
  const m = imageUrl.match(/Special:FilePath\/(.+)$/);
  if (!m) return null;
  return "File:" + decodeURIComponent(m[1]);
}

function extFromUrl(url: string): string {
  const m = url.match(/\.([a-zA-Z0-9]+)(?:\?|$)/);
  return (m ? m[1] : "jpg").toLowerCase();
}

async function fetchJSON(url: string): Promise<any> {
  for (let attempt = 0; attempt < 3; attempt++) {
    const res = await fetch(url, { headers: { "User-Agent": UA } });
    if (res.status === 429 || res.status >= 500) { await sleep(2000 * (attempt + 1)); continue; }
    if (!res.ok) throw new Error(`Commons ${res.status}: ${url}`);
    return res.json();
  }
  throw new Error(`Commons retries exhausted: ${url}`);
}

async function download(url: string, dest: string): Promise<void> {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`download ${res.status}: ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  await writeFile(dest, buf);
}

/** Path of this Q-id's image on disk, or null. */
function imagePath(id: string): string | null {
  for (const ext of EXTS) {
    const p = `${IMG_DIR}/${id}.${ext}`;
    if (existsSync(p)) return p;
  }
  return null;
}

/** Presence-skip: image file for this Q-id already on disk AND a credit entry exists. */
function alreadyHave(id: string, credits: ImageCredits): boolean {
  if (FORCE) return false;
  if (!credits[id]) return false;
  return imagePath(id) !== null;
}

function fmtBytes(n: number): string {
  if (n >= 1 << 20) return `${(n / (1 << 20)).toFixed(1)} MB`;
  if (n >= 1 << 10) return `${(n / (1 << 10)).toFixed(0)} KB`;
  return `${n} B`;
}

function renderReport(credits: ImageCredits, nameById: Map<string, string>): string {
  const ids = Object.keys(credits);
  const isFree = (c: ImageCredit) => {
    const k = (c.licenseCategory ?? c.licenseShort ?? "").toLowerCase();
    // Recognize the CC/PD families plus the older free-license names Commons still emits:
    // GFDL, "Attribution" (a free-reuse tag), "Copyrighted free use", "No restrictions".
    return /^cc|^pd|public domain|^cc0|gfdl|attribution|free use|no restrictions/.test(k);
  };
  let full = 0, partial = 0, bare = 0;
  const byLicense: Record<string, number> = {};
  const flagged: string[] = [];
  // Size, measured from files on disk (covers presence-skipped files from prior runs too).
  const sizes: { id: string; bytes: number }[] = [];
  let totalBytes = 0, onDisk = 0;
  const buckets = { "<50 KB": 0, "50–150 KB": 0, "150–300 KB": 0, "300 KB–1 MB": 0, ">1 MB": 0 };

  for (const id of ids) {
    const c = credits[id];
    const hasAuthor = !!c.author, hasLicense = !!c.licenseShort;
    if (hasAuthor && hasLicense) full++;
    else if (hasAuthor || hasLicense) partial++;
    else bare++;
    const lic = c.licenseShort ?? "(none)";
    byLicense[lic] = (byLicense[lic] ?? 0) + 1;
    if (!isFree(c)) flagged.push(`- \`${id}\` — license=\`${c.licenseShort ?? "?"}\` category=\`${c.licenseCategory ?? "?"}\` author=${c.author ? `\`${c.author}\`` : "—"}`);

    const p = imagePath(id);
    if (p) {
      const bytes = statSync(p).size;
      sizes.push({ id, bytes });
      totalBytes += bytes;
      onDisk++;
      if (bytes < 50 * 1024) buckets["<50 KB"]++;
      else if (bytes < 150 * 1024) buckets["50–150 KB"]++;
      else if (bytes < 300 * 1024) buckets["150–300 KB"]++;
      else if (bytes < 1 << 20) buckets["300 KB–1 MB"]++;
      else buckets[">1 MB"]++;
    }
  }
  sizes.sort((a, b) => b.bytes - a.bytes);
  const mean = onDisk ? totalBytes / onDisk : 0;
  const outliers = sizes.slice(0, 20).map((s) =>
    `- \`${s.id}\` — ${fmtBytes(s.bytes)}${nameById.get(s.id) ? ` (${nameById.get(s.id)})` : ""}`);

  const lines = [
    "# Image attribution coverage",
    "",
    "Auto-generated by `fetch:images`. Reports over the full `data/image-credits.json`.",
    "",
    `**Total images (credited):** ${ids.length}  |  **on disk:** ${onDisk}`,
    "",
    "## Payload size",
    `- **Total on disk:** ${fmtBytes(totalBytes)} across ${onDisk} files`,
    `- **Mean:** ${fmtBytes(mean)}  |  **Largest:** ${sizes.length ? fmtBytes(sizes[0].bytes) : "—"}`,
    "",
    "Distribution:",
    ...Object.entries(buckets).map(([k, v]) => `- ${k}: ${v}`),
    "",
    "### Heaviest 20 (candidates for a local downscale/recompress pass)",
    outliers.length ? "" : "_No files on disk._",
    ...outliers,
    "",
    "## Completeness",
    `- Full (author + license): ${full}`,
    `- Partial (one missing): ${partial}`,
    `- Bare (neither): ${bare}`,
    "",
    "## By license",
    ...Object.entries(byLicense).sort((a, b) => b[1] - a[1]).map(([k, v]) => `- ${k}: ${v}`),
    "",
    `## Flagged — not recognized as free (${flagged.length})`,
    flagged.length ? "" : "_None — every image parses as a CC/PD license._",
    ...flagged,
    "",
  ];
  return lines.join("\n");
}

async function main() {
  const raws: RawTaxon[] = JSON.parse(await readFile("data/raw-taxa.json", "utf8"));
  const withImage = raws.filter((r) => r.imageUrl);
  const nameById = new Map(raws.map((r) => [r.id, r.name]));
  await mkdir(IMG_DIR, { recursive: true });

  let credits: ImageCredits = {};
  try { credits = JSON.parse(await readFile(CREDITS_PATH, "utf8")); } catch { /* first run */ }

  let fetched = 0, skipped = 0, failed = 0;
  for (const r of withImage) {
    if (alreadyHave(r.id, credits)) { skipped++; continue; }
    const title = fileTitleFromUrl(r.imageUrl!);
    if (!title) { failed++; console.warn(`no File: title for ${r.id} (${r.imageUrl})`); continue; }
    const url = `${API}?action=query&format=json&prop=imageinfo&iiprop=extmetadata%7Curl&iiurlwidth=${THUMB_WIDTH}&titles=${encodeURIComponent(title)}`;
    try {
      const j = await fetchJSON(url);
      const page: any = Object.values(j.query?.pages ?? {})[0];
      const ii = page?.imageinfo?.[0];
      if (!ii?.thumburl) { failed++; console.warn(`no thumburl for ${r.id} (${title})`); continue; }
      const em = ii.extmetadata ?? {};
      const val = (k: string) => (em[k]?.value as string | undefined);
      const credit: ImageCredit = {
        author: sanitizeArtist(val("Artist")),
        licenseShort: val("LicenseShortName"),
        licenseUrl: val("LicenseUrl"),
        licenseCategory: val("License"),
        sourceFileUrl: ii.url,
      };
      const ext = extFromUrl(ii.thumburl);
      await download(ii.thumburl, `${IMG_DIR}/${r.id}.${ext}`);
      credits[r.id] = credit;
      fetched++;
      if (fetched % 25 === 0) {
        await writeFile(CREDITS_PATH, JSON.stringify(credits, null, 0)); // periodic flush
        console.log(`images: ${fetched} fetched, ${skipped} skipped`);
      }
      await sleep(1000); // ~1 req/sec, be polite
    } catch (e) {
      failed++;
      console.warn(`image ${r.id} failed:`, (e as Error).message);
    }
  }

  // Wrap the final flush: a disk-write throw here would otherwise crash the run (and skip the
  // report) after losing up to 24 credit entries gathered since the last periodic flush. Log it
  // instead — a re-run's presence-skip recovers those entries anyway.
  try {
    await writeFile(CREDITS_PATH, JSON.stringify(credits, null, 0));
  } catch (e) {
    console.error(
      `final credits flush to ${CREDITS_PATH} failed (up to 24 entries since the last periodic ` +
        `flush not persisted; a re-run recovers them via presence-skip):`,
      (e as Error).message,
    );
  }
  await mkdir("docs/superpowers", { recursive: true });
  await writeFile(REPORT_PATH, renderReport(credits, nameById));

  console.log("=== Mesozooa image harvest ===");
  console.log(`images referenced: ${withImage.length}`);
  console.log(`fetched this run:  ${fetched}`);
  console.log(`skipped (present): ${skipped}`);
  console.log(`failed:            ${failed}`);
  console.log(`credits total:     ${Object.keys(credits).length}`);
  console.log(`report:            ${REPORT_PATH} (payload size + outliers inside)`);
}

main().catch((e) => { console.error(e); process.exit(1); });
